### ISSUE TITLE
Please Suggest a file manager among these

### ISSUE THREAD

**Issue by KAGEYAM4** [ibraheemdev/modern-unix#136]
I was looking to learning a tui file-manager, and the list of tui-file manager is quite big and i am not able to differentiate between them
https://wiki.archlinux.org/title/Midnight_Commander
https://github.com/ranger/ranger
https://github.com/sxyazi/yazi
https://github.com/dylanaraps/fff
https://github.com/kamiyaa/joshuto
https://github.com/jarun/nnn
https://github.com/sayanarijit/xplr
https://vifm.info

Is there no one among these that can be added to this repo to be called moden & following unix philosophy?

**Comment by chapmanjacobd** [comment]
Midnight Commander is solid but yes it is a bit old-school.

xplr looks promising, but I'm not sure if the idea of a file manager can really follow unix philosophy.

On desktop I definitely prefer Krusader (which is similar to MC) but honestly I hardly ever use it. 

Instead I use:

- fd-find: For searching filenames, file extensions, etc `fd -eRAR --min-depth 1 --max-depth 2 --created-within '1 week'
- rclone move to merge file trees
- `NOCOLOR=1 ncdu` for sorting files by size or count of files (press c and shift-c)
- `lsar` to browse archives (part of `unar` I think)
- `rename` from `util-linux`
- I created these fish functions to quickly browse file trees but I honestly don't use them that often because `ncdu` is usually more useful:

function f
    setterm -linewrap off
    tree -FLh 3 --sort=mtime --dirsfirst --prune --du --noreport -up -C $argv | grep -v '/$'
    setterm -linewrap on
end

function l
    setterm -linewrap off
    tree -Lh 2 --sort=mtime --dirsfirst -d -h --prune --du -up -C $argv
    setterm -linewrap on
end

(You can use `f -L 3` to see three levels of files)

I'm not sure what you would need a file manager for beyond these tasks ?

**Comment by sxyazi** [comment]
Check out Yazi, https://github.com/sxyazi/yazi :

- 💥 **Blazing fast** - Written in Rust, it is the only terminal file manager that is fully asynchronous I/O, event-driven, and supports multi-threading for accelerated CPU tasks.
- 🌟 **Batteries included** - It includes various image protocols and integrates Überzug++ to cover almost all terminal image displays. It also has built-in code highlighting and native integration with `fd`, `rg`, `fzf`, and `zoxide`.
- 🎨 **Modern** - Yazi has a comprehensive theme system with multiple themes to choose from. It also supports Vim-like input, select components, and multiple tabs.
- 💪 **Powerful** - It boasts the most powerful asynchronous task scheduling system, and has a concurrent plugin system that allows easy creation of custom previewers, preloaders, and UI plugins, etc.
- 🦆 Bonus: The duck is a cute fellow.

Also see this article: [Why is Yazi Fast?](https://github.com/sxyazi/yazi/issues/143)

![1](https://github.com/ibraheemdev/modern-unix/assets/17523360/e447e294-6abc-41c9-bc24-47016224a392)

![2](https://github.com/ibraheemdev/modern-unix/assets/17523360/0874b576-e636-40d0-90ee-d6cbd2c6d2bc)

**Comment by KAGEYAM4** [comment]
I am also leaning towards yazai.

**Comment by kirkserverhl** [comment]
choosing yazyi was one of the greatest decisions i have made ever and  am the father of 2 beautiful children and one that thas a really large fourhead, they all use yazi and really didn't like ranger because they sai d it was 'poopy'
